### ISSUE TITLE
Installation file request 

### ISSUE THREAD

**Issue by pdimu** [Areoxy/WinTube#1]
good to know that the latest release was in 2022, but it's better to continue. you can also opt to upload it to ms store and even put a price if you want (i recommend not to do it though, as the others are paid and awful). it's a great project and i really want to see it rise up in the eyes of the community of win 11 users

**Comment by pdimu** [comment]
omg... TWO YEARS
and if you want help, can't do with the code but the docs to do it. ask if want or say if this is closed (the project)

**Comment by Areoxy** [comment]
I am currently working on a new release, which will be released in a few days. I will also upload a setup installer when the new version of WinTube is finished.

**Comment by Areoxy** [comment]
@okgamr I've released a new version of WinTube now and will add the setup installer within a week. To see whats new read the changes listed in the release. Have a nice day!

**Comment by pdimu** [comment]
Thanks! I'm glad you reopened the project. And also, don't give up!

**Comment by pdimu** [comment]
I finally managed to download the latest version (cuz I already implemented the other one with vs aka took time to remove it) but there wasn't any setup there - again

**Comment by Areoxy** [comment]
> I finally managed to download the latest version (cuz I already implemented the other one with vs aka took time to remove it) but there wasn't any setup there - again

I am sorry about that but I'll create the setup now It'll be available in a few minutes. I'm gonna add the setup to the latest release then

**Comment by Areoxy** [comment]
> > I finally managed to download the latest version (cuz I already implemented the other one with vs aka took time to remove it) but there wasn't any setup there - again
> 
> I am sorry about that but I'll create the setup now It'll be available in a few minutes. I'm gonna add the setup to the latest release then

I've just added the setup file for the newest version of wintube. I also tested the installer in a vm on that never was any version of wintube installed before and it worked 👍

**Comment by pdimu** [comment]
Thank you!
